// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int times = Integer.parseInt(args[0]);
		int i = 0;
		int big = 0;
		int small = 0;
		double Ratio;
		while (times>i) {
			double rand = Math.random();
			if (rand>0.5) {
				++big;
			}
			else{
				++small;
			}
			i++;		
		}
		if (big==0 || small==0) {
			System.out.println("> 0.5: " + big);
			System.out.println("<= 0.5: " + small);
			
		}
		else{
			System.out.println("> 0.5: " + big);
			System.out.println("<= 0.5: " + small);
			if (big>small) {
				Ratio = (double) small/big;
				System.out.println("Ratio: " +  Ratio);
			}
			else{
				Ratio = (double) big/small;
				System.out.println("Ratio: " + Ratio);
			}
		}

	}
}
